language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3

    # The SDK version used to compile
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulators
#    - sys-img-x86-android-28

before_install:
  - chmod +x gradlew
